### ISSUE TITLE
Bids Controller

### ISSUE THREAD

**Issue by PercyODI** [rmmartin08/Stage2.PieAuction#1]
## Story

As a consumer of the backend API,
I want to create bids
So that pies can be bid on

---

## Notes:

- This will need to be a new controller that supports a HttpPost action. 
- Expected endpoint should be http://localhost:15665/api/bids
- See the ERD Diagram at https://github.com/PercyODI/Stage2.PieAuction/blob/master/Instruction.Images/ERD.jpg for what bids should look like

**Comment by rmmartin08** [comment]
working on this issue
